CREATE TABLE ORDERS(
Order_ID	serial primary key,
Customer_ID	int,
Book_ID	int,
Order_Date	date,
Quantity	int,
Total_Amount	decimal(10,2)
);

COPY ORDERS (Order_ID,	Customer_ID,Book_ID,Order_Date,Quantity,Total_Amount)
FROM 'C:/Data Analytics/MySql/Practice/ST - SQL ALL PRACTICE FILES/All Excel Practice Files/Orders.csv'
DELIMITER ','
CSV HEADER;


-- DATE & TIME FUNCTIONS

-- NOW()

SELECT NOW() AS CURRENT_DATE_TIME;

-- CURRENT_DATE()

SELECT CURRENT_DATE AS TODAYS_DATA;

SELECT
	ORDER_DATE,
	(CURRENT_DATE - ORDER_DATE) AS DAYS_DIFF
FROM
	ORDERS;

-- CURRENT_TIME()

SELECT CURRENT_TIME AS NOW_TIME;

-- TO CHAR()

SELECT TO_CHAR(ORDER_DATE,'DD-MON-YYYY') FROM ORDERS;

-- AGE()

SELECT AGE(CURRENT_DATE , ORDER_DATE) AS AGE_SINCE_ORDERED FROM ORDERS;

-- EXTRACT()

SELECT
	EXTRACT(
		YEAR
		FROM
			ORDER_DATE
	) AS ORDER_YEAR,
	EXTRACT(
		MONTH
		FROM
			ORDER_DATE
	) AS ORDER_MONTH,
	EXTRACT(
		DAY
		FROM
			ORDER_DATE
	) AS ORDER_DAY
FROM
	ORDERS;


-- DATE PART()

SELECT DATE_PART('DOW',ORDER_DATE) AS DAY_OF_WEEK,
	DATE_PART('MONTH',ORDER_DATE) AS MONTHS
FROM ORDERS;

-- DATE TRUNC

SELECT ORDER_DATE,DATE_TRUNC('WEEK', ORDER_DATE) AS WEEK_START FROM ORDERS;

-- INTERVAL 

SELECT ORDER_DATE, ORDER_DATE+INTERVAL '14 DAYS' AS NEW_DATE
FROM ORDERS;


-- TO_DATE

SELECT TO_DATE('2024-11-25', 'YYYY-MM-DD') AS CONVERTED_DATE;

SELECT * FROM ORDERS;